### PR TITLE
Restrict viewer api route

### PR DESCRIPTION
**Pull request by idugan100**
goals

- pull viewer into Laravel
- refactor requested route for map to be a env variable
- redo map request to use infinite token with the api

### CODE REVIEW

**Comment by idugan100** [comment]
This is working properly

- viewer is now under Laravel project
- viewer is using API route with token which is set in .env 
- internal routes are removed
- my-app folder is removed

I will do some preliminary testing and then assign this for review with testing instructions.

**Comment by idugan100** [comment]
##Set up instructions

- git fetch
- git checkout restrict_viewer_api_route
- cd tile backend
- npm install --force (this will install open layers into the Laravel project)
- in .env set APP_URL to your local development url
- create account locally and get an api key
- go into the personal_access_tokens table and increase the usage for that key to 100000
- in the .env file set OL_KEY equal to the key you created and increased the usage limit on
- php artisan serve
- nom run dev

##Changes Made

Previously, we had the open layers viewer as a separate application. It used special internal routes to fetch the tiles. Now, the viewer is contained in the Laravel app which will make things simpler. I removed the internal routes and updated the open layers javascript to use an api key that we set in the .env file, so the viewer can use the same api route another developer would use. We will manually increase the limit on that api key as 100 request would be made very quickly with the viewer.

##Testing Instructions

test that the viewer is working properly as well as all the informational pages. You can review the code written by clicking on the commits earlier in the thread. Commits 2 and 3 involve deleting my-app folder so they will have a ton of changes and don't need to be reviewed.

**Comment by bryanYoder** [comment]
Followed all setup instructions successfully, and started servers. Informational pages are working fine, the viewer is not displaying any data, and the background map does not change when shifting position/zooming. The token is reading no uses. I will look to troubleshoot before meeting on Thursday.

**Comment by idugan100** [comment]
I would double check that your APP_URL value is exactly the link from php artisan serve. The default is "http://localhost",  but largon gives you the link "http://127.0.0.1:8000".

**Comment by bryanYoder** [comment]
That was the issue, everything works now

**Pull request merged**
